version: '3.8'

services:
  php:
    build:
      context: ./immo-api-php
      dockerfile: Dockerfile
    volumes:
      - ./immo-api-php:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=immo_db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=immo_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
